/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

namespace Corsinvest.ProxmoxVE.Report;

/// <summary>
/// Branding information shown on the report cover page.
/// Override when embedding cv4pve-report in another application.
/// </summary>
public class ReportInfo
{
    /// <summary>
    /// Application name shown on the cover page (e.g. "cv4pve-admin").
    /// Defaults to the entry assembly name, or "cv4pve-report" if not available.
    /// </summary>
    public string ApplicationName { get; set; } = "cv4pve-report";

    /// <summary>
    /// Application version shown on the cover page.
    /// Defaults to the entry assembly version, or the cv4pve-report library version.
    /// </summary>
    public string ApplicationVersion { get; set; } =
        typeof(ReportEngine).Assembly.GetName().Version?.ToString(3) ?? string.Empty;

    /// <summary>
    /// URL linked on the cover page "Generated by" row.
    /// </summary>
    public string ApplicationUrl { get; set; } = "https://github.com/Corsinvest/cv4pve-report";
}
